-- Add manual_content column to products table (if it doesn't exist)
ALTER TABLE products ADD COLUMN manual_content LONGTEXT;

-- Update sample products with manual content
UPDATE products SET manual_content = '<h3>3D-printer - Bruksanvisning</h3><p>Denne 3D-printeren brukes til å printe 3D-objekter fra digitale modeller.</p><h4>Sikkerhetsregler:</h4><ul><li>Påse at området omkring printeren er ryddig</li><li>Ikke berør den varme dysen mens printeren er i gang</li><li>Vent minst 2 timer før du fjerner printet</li></ul><h4>Steg-for-steg instruksjoner:</h4><ol><li>Forhåndsoppvarming av printeren</li><li>Last opp G-koden via USB eller SD-kort</li><li>Juster dysen høyde</li><li>Start printingen</li><li>Overvår printingen</li></ol>' WHERE id = 1;

UPDATE products SET manual_content = '<h3>Laser Cutter - Bruksanvisning</h3><p>Laserskjæreren brukes til å grave eller kutte materialer som tre, akryl og lær.</p><h4>Sikkerhetsregler:</h4><ul><li>Bruk alltid sikkerheitsbriller</li><li>Påse at skilleveggen omkring enheten er lukket</li><li>Ikke berør laseråpningen</li><li>Sørg for ventilasjon</li></ul><h4>Materialer som kan brukes:</h4><ul><li>Tre (ikke behandlet)</li><li>Akryl</li><li>Lær (naturlig)</li><li>Papir og papp</li></ul>' WHERE id = 2;

UPDATE products SET manual_content = '<h3>CNC Mill - Bruksanvisning</h3><p>CNC-fresemaskinen brukes til presisjonsskjæring og bearbeiding av materialer.</p><h4>Sikkerhetsregler:</h4><ul><li>Bruk alltid sikkerheitsbriller</li><li>Fjern løs tøy og smykker</li><li>Aldri berør den roterende spindelen</li><li>Sikre materialet godt før fresing</li></ul><h4>Typiske operasjoner:</h4><ul><li>Boring</li><li>Fresing</li><li>Skjæring</li><li>Gravering</li></ul>' WHERE id = 3;

UPDATE products SET manual_content = '<h3>Soldering Station - Bruksanvisning</h3><p>Lodestasjonenen brukes til elektronisk lodning og komponentmontering.</p><h4>Sikkerhetsregler:</h4><ul><li>Aldri berør loddebakken som er varm</li><li>Bruk alltid sikkerheitsverktøy</li><li>Sørg for god ventilasjon</li><li>La alt kjøle av før oppbevaring</li></ul><h4>Fremgangsmåte:</h4><ol><li>Kalibrér loddebakken til rett temperatur</li><li>Påfør lodd på jernspissen</li><li>Tilføy litt loddetinn</li><li>Hold jernspissen mot kontaktene</li><li>Fjern aldri jernen mens tinnet er flytende</li></ol>' WHERE id = 4;

UPDATE products SET manual_content = '<h3>Vinyl Cutter - Bruksanvisning</h3><p>Vinyl cutter brukes til å skjære dekorativt vinyl for klistremerker og dekorasjoner.</p><h4>Påkrevd materiale:</h4><ul><li>Vinyl rull (selvklebende)</li><li>Skraper for fjerning av linjer</li></ul><h4>Steg-for-steg:</h4><ol><li>Last opp design i RhinoCAM eller annen software</li><li>Kalibrér maskinen</li><li>Last vinyl på maskinen</li><li>Kjør snittsekvensen</li><li>Fjern den unødvendige vinyl med skraper</li></ol>' WHERE id = 5;

UPDATE products SET manual_content = '<h3>Electronics Bench - Bruksanvisning</h3><p>Elektronikk arbeidsbenken er et fullt utstyrt elektro laboratorium.</p><h4>Tilgjengelige verktøy:</h4><ul><li>Digitalt multimeter</li><li>Oscilloskop</li><li>Lodestasjon</li><li>Kabel og komponenter</li><li>Strømforsyning</li></ul><h4>Regler:</h4><ul><li>Aldri la komponenter på gulvet</li><li>Påse at alt er ryddet etter bruk</li><li>Slå av alle enheter før du forlater benken</li><li>Rapportér brutt utstyr umiddelbart</li></ul>' WHERE id = 6;
